<?php


namespace FNDEV\Tests\Unit\Models\Resources;


use FNDEV\Tests\TestCase;
use FNDEV\vShpare\Api\VM\Resources\Hardware\Hardware;
use FNDEV\vShpare\Api\VM\Resources\Resources;

class ResourcesTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function test_get_hardware_handler(){
        $resources=new Resources($this->vmwareApiClient);
        $this->assertInstanceOf(Hardware::class,$resources->hardware());
    }
}